BEGIN TRANSACTION;CREATE TABLE PLAYERS 
                (
                    NAME VARCHAR(50) PRIMARY KEY, 
                    PASSWORD VARCHAR(50),
                    POINTS INTEGER
                );INSERT INTO "PLAYERS" VALUES('Alejo','Venus',4);INSERT INTO "PLAYERS" VALUES('Venus','Alejo',66);INSERT INTO "PLAYERS" VALUES('test','234',0);INSERT INTO "PLAYERS" VALUES('a','a',80);INSERT INTO "PLAYERS" VALUES('Imad','Venus',0);INSERT INTO "PLAYERS" VALUES('s','s',79);INSERT INTO "PLAYERS" VALUES('z','z',0);INSERT INTO "PLAYERS" VALUES('Chino','Lourdes',2);COMMIT;